version: "3"

services:
  postgres:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    tmpfs: /var/lib/postgresql/data

  mongo:
    image: mongo:4
    environment:
      - MONGO_INITDB_DATABASE=brotherhood
    ports:
      - 27017:27017
    volumes:
      - ./.docker/volumes/mongo-data:/data/db
      - ./.docker/mongo/entrypoint:/docker-entrypoint-initdb.d
